<a href="https://colab.research.google.com/github/Aswinibishoyi/3.Data-Preprocessing/blob/master/Dimensionality_Reduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The number of input variables or features for a dataset is referred to as its dimensionality. Dimensionality reduction reduces the number of input variables. More input features often make a predictive modeling task more challenging So, referred to as the curse of dimensionality.
A classification or regression dataset uses it in order to better fit a predictive model.
So, i)Large numbers of input features can cause poor performance for machine learning algorithms, ii)Dimensionality reduction reduces the number of input features, iii)Dimensionality reduction methods include feature selection, linear algebra methods, projection methods, and autoencoders.

Techniques for Dimensionality Reduction
1)Feature Selection Methods
2)Linear Algebra Methods
3)Projection Methods
4)Autoencoder Methods


# Calculate Principal Component Analysis (PCA) from Scratch in Python

In [2]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# calculate the mean of each column
M = mean(A.T, axis=1)
print(M)
# center columns by subtracting column means
C = A - M
print(C)
# calculate covariance matrix of centered matrix
V = cov(C.T)
print(V)
# eigendecomposition of covariance matrix
values, vectors = eig(V)
print(vectors)
print(values)
# project data
P = vectors.T.dot(C.T)
print(P.T)

[[1 2]
 [3 4]
 [5 6]]
[3. 4.]
[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]
[[4. 4.]
 [4. 4.]]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[8. 0.]
[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]
